version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: wordpress_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./db/backup.sql:/docker-entrypoint-initdb.d/backup.sql
      - ./db/custom_updates.sql:/docker-entrypoint-initdb.d/custom_updates.sql
      # - ./db/.env:/docker-entrypoint-initdb.d/.env   # did not works
      # - ./db/custom_updates.sh:/docker-entrypoint-initdb.d/custom_updates.sh # did not works
    environment:
      APACHE_RUN_USER: '#1000'
      APACHE_RUN_GROUP: '#1000'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB_PORT: ${MYSQL_DB_PORT}
    ports:
      - target: 3306
        published: ${MYSQL_DB_PORT}
    networks:
      - wordpress_network

    # ports:
    #   - ${MYSQL_DB_PORT}:3306
      # - "3002:3306"


  wordpress:
    depends_on:
      - db
    build: .
    restart: always
    container_name: wordpress_app
    ports:
      - "${WORDPRESS_PORT}:80"  # Use the port from the .env file
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}:${MYSQL_DB_PORT}
      WORDPRESS_DB_HOST_PORT: ${WORDPRESS_DB_HOST_PORT}
      # WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_PORT: ${MYSQL_DB_PORT}
    volumes:
      - ./wordpress:/var/www/html
      # - .:/var/www/html/
    networks:
      - wordpress_network
  
volumes:
  db_data:
      
networks:
  wordpress_network:
    driver: bridge