version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: wordpress_db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
      # - ./path/to/your/mysql-dump.sql:/docker-entrypoint-initdb.d/mysql-dump.sql
      # command: --default-authentication-plugin=mysql_native_password mysqld --innodb_log_file_size=128M --max_allowed_packet=32M --sql_mode="
    command: "--default-authentication-plugin=mysql_native_password"
    ports:
      - "3002:3306"

  wordpress:
    depends_on:
      - db
    build: .
    container_name: wordpress_app
    restart: always
    ports:
      - "${WORDPRESS_PORT}:80"
      - "443:443"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
      # - ./path/to/your/local/wordpress:/var/www/html

volumes:
  db_data:
  wordpress_data: